window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.azerbaijan = [
  {
    id: 'lankaran-tea',
    name: '连科兰茶',
    nameEn: 'Lankaran Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '阿塞拜疆',
    province: '连科兰区',
    city: '连科兰',
    description: '连科兰茶沐浴着里海西南岸的温润海风，在连科兰低地的肥沃土壤中悄然成长。茶汤如琥珀般温润透彻，入口柔和细腻，带着轻甜的花香与淡淡的果脯蜜韵。在阿塞拜疆的每一个家庭中，连科兰红茶是待客的最高礼仪，是这片土地最真挚的温度。',
    history: '连科兰是阿塞拜疆最重要的茶叶产区，茶产业始于20世纪30年代苏联时期。得益于里海沿岸的亚热带气候，这里的茶园蓬勃发展，成为高加索地区继格鲁吉亚之后的又一重要茶叶基地。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种、连科兰选育品种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级、二级',
    characteristics: '条索紧结乌润，汤色琥珀明亮，花香蜜甜清雅，口感柔和细润',
    tags: ['阿塞拜疆茶', '连科兰', '里海', '花香', '柔和', '高加索'],
    routes: []
  },
  {
    id: 'lenkoran-green',
    name: '连科兰绿茶',
    nameEn: 'Lenkoran Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '阿塞拜疆',
    province: '连科兰区',
    city: '连科兰',
    description: '连科兰绿茶在阿塞拜疆的茶版图上独树一帜，如同里海边悄然绽放的清新之花。炒青工艺赋予它轻盈的豆香与清冽甘爽的滋味，茶汤嫩绿如连科兰春日的新叶。在这红茶为尊的国度里，这一抹绿意代表着阿塞拜疆茶文化的多元与包容。',
    history: '连科兰地区的绿茶生产近年来才逐步兴起，为满足日益增长的多样化消费需求，当地茶企开始利用本土原料开发绿茶产品，市场反响良好。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '连科兰本地品种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索紧实翠绿，豆香清新淡雅，汤色嫩绿明亮，滋味清冽回甘',
    tags: ['阿塞拜疆茶', '连科兰', '绿茶', '清冽', '豆香', '里海'],
    routes: []
  },
  {
    id: 'astara-tea',
    name: '阿斯塔拉红茶',
    nameEn: 'Astara Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '阿塞拜疆',
    province: '阿斯塔拉区',
    city: '阿斯塔拉',
    description: '阿斯塔拉红茶生长于阿塞拜疆与伊朗交界的边境地带，里海的风与塔雷什山脉的清泉共同滋养着这片茶园。茶汤深红浓烈如阿斯塔拉暮色中的天际，口感强劲有力，麦芽的甜香与轻微的果酸交织，回味悠长。在这片边境之地上，红茶是两国文化交融的芬芳纽带。',
    history: '阿斯塔拉区紧邻伊朗，是阿塞拜疆南部的茶叶产区。苏联时期这里就建立了茶叶加工厂，以CTC红碎茶为主要产品，大量供应国内市场并出口至苏联其他加盟共和国。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种',
    production: '采摘、萎凋、揉切（CTC）、发酵、干燥',
    grades: 'BOP、BP',
    characteristics: '颗粒紧实，汤色深红浓烈，麦芽甜香突出，口感强劲回甘持久',
    tags: ['阿塞拜疆茶', '阿斯塔拉', '边境茶', '浓烈', '麦芽香', '红碎茶'],
    routes: []
  }
];