window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.bangladesh = [
  {
    id: 'sylhet-ctc',
    name: '锡尔赫特CTC红茶',
    nameEn: 'Sylhet CTC Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '锡尔赫特区',
    city: '锡尔赫特',
    description: '锡尔赫特CTC红茶是孟加拉国茶产业的脊梁，翻滚切割的工艺赋予它浓烈如热带暴雨般的强劲口感。茶汤深红如陈年琥珀，麦芽香与焦糖甜交织翻涌，最适合与牛奶和糖共舞。它是孟加拉人清晨醒来的第一口甘露，也是这个国度最温暖的记忆。',
    history: '锡尔赫特是孟加拉国茶业的发源地，自19世纪英殖民时期起便大规模开辟茶园。CTC工艺传入后，锡尔赫特迅速成为南亚重要的红碎茶生产基地，支撑起庞大的国内消费与出口。',
    chronology: [
      { period: '19世纪（英殖民时期）', title: '锡尔赫特茶业发源', content: '锡尔赫特是孟加拉国茶业的发源地，自19世纪英殖民时期起便大规模开辟茶园。' },
      { period: '20世纪', title: 'CTC工艺引入与扩张', content: 'CTC工艺传入后，锡尔赫特迅速成为南亚重要的红碎茶生产基地，支撑起庞大的国内消费与出口。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、TV系列无性系',
    production: '采摘、萎凋、揉切（CTC）、发酵、干燥',
    grades: 'BOP、BP、OF、PD、Dust',
    characteristics: '颗粒均匀乌润，麦芽焦糖香浓郁，汤色深红明亮，口感浓强醇厚',
    tags: ['孟加拉茶', '锡尔赫特', 'CTC', '红碎茶', '浓强', '麦芽香', '奶茶伴侣'],
    routes: []
  },
  {
    id: 'srimangal-orthodox',
    name: '斯里曼加尔正统红茶',
    nameEn: 'Srimangal Orthodox Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '锡尔赫特区',
    city: '斯里曼加尔',
    description: '斯里曼加尔正统红茶被誉为孟加拉茶都的骄傲，传统工艺慢工细作，将热带雨林的气息封存于每一片茶叶中。茶汤橙黄明亮，轻柔的花香裹着淡淡的蜜甜在舌尖缓缓绽放。在这座茶园环绕的小镇，时光仿佛慢了半拍，只为等待一杯好茶的诞生。',
    history: '斯里曼加尔是孟加拉国的茶都，拥有全国最集中的茶园和茶叶研究所。正统工艺红茶是当地的高端产品，在国际市场上享有盛誉。',
    chronology: [
      { period: '20世纪', title: '茶都崛起', content: '斯里曼加尔是孟加拉国的茶都，拥有全国最集中的茶园和茶叶研究所。' },
      { period: '当代', title: '高端正统红茶', content: '正统工艺红茶是当地的高端产品，在国际市场上享有盛誉。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: 'BT系列无性系、阿萨姆种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: 'FTGFOP、TGFOP、GFOP',
    characteristics: '条索紧秀乌润，花香蜜甜清雅，汤色橙黄明亮，滋味柔滑回甘',
    tags: ['孟加拉茶', '斯里曼加尔', '正统红茶', '茶都', '花香', '蜜甜', '柔滑'],
    routes: []
  },
  {
    id: 'maulvibazar-tea',
    name: '毛尔维巴扎尔茶',
    nameEn: 'Maulvibazar Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '锡尔赫特区',
    city: '毛尔维巴扎尔',
    description: '毛尔维巴扎尔茶园被翠绿的丘陵层层环抱，清新的山风与充足的雨水滋养出品质卓越的红茶原料。茶汤浓烈鲜活，带着热带大地的粗犷与热烈，苦涩之后是持久的甘甜回味。它是这片土地上茶农汗水与希望的凝结。',
    history: '毛尔维巴扎尔是锡尔赫特茶区的重要组成部分，茶园遍布低山丘陵。这里的茶叶加工厂历史逾百年，见证了孟加拉国茶产业的起落与复兴。',
    chronology: [
      { period: '19世纪', title: '百年茶园起步', content: '毛尔维巴扎尔是锡尔赫特茶区的重要组成部分，茶园遍布低山丘陵。' },
      { period: '百年发展至今', title: '茶产业起落与复兴', content: '这里的茶叶加工厂历史逾百年，见证了孟加拉国茶产业的起落与复兴。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、TV系列',
    production: '采摘、萎凋、揉切（CTC）、发酵、干燥',
    grades: 'BOP、BP、OF、Dust',
    characteristics: '颗粒紧结，浓强鲜爽，麦芽香突出，汤色深红厚重，冷后浑明显',
    tags: ['孟加拉茶', '毛尔维巴扎尔', '红碎茶', '浓强', '麦芽', '热带风味'],
    routes: []
  },
  {
    id: 'habiganj-ctc',
    name: '哈比甘杰CTC红茶',
    nameEn: 'Habiganj CTC Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '锡尔赫特区',
    city: '哈比甘杰',
    description: '哈比甘杰CTC红茶以稳定而均衡的品质赢得市场青睐，宛若一位忠厚可靠的老友。茶汤深褐透亮，口感醇厚扎实，麦芽与坚果的香气层次分明。每日清晨的一杯哈比甘杰奶茶，便是孟加拉人简单而踏实的幸福。',
    history: '哈比甘杰的茶产业与锡尔赫特同步发展，拥有多个历史悠久的大型茶园。其CTC生产线现代化程度较高，产品大量供应国内市场和出口中东地区。',
    chronology: [
      { period: '20世纪', title: '与锡尔赫特同步发展', content: '哈比甘杰的茶产业与锡尔赫特同步发展，拥有多个历史悠久的大型茶园。' },
      { period: '当代', title: '现代化与出口中东', content: '其CTC生产线现代化程度较高，产品大量供应国内市场和出口中东地区。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: 'TV系列无性系',
    production: '采摘、萎凋、揉切（CTC）、发酵、干燥',
    grades: 'BOP、BP、Dust',
    characteristics: '颗粒匀整，汤色褐红油亮，坚果麦芽香，滋味醇和厚实，冷后浑佳',
    tags: ['孟加拉茶', '哈比甘杰', 'CTC', '坚果香', '醇厚', '日常茶饮'],
    routes: []
  },
  {
    id: 'chittagong-tea',
    name: '吉大港山茶',
    nameEn: 'Chittagong Hill Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '吉大港区',
    city: '兰加马蒂',
    description: '吉大港山茶生长于孟加拉国东南部吉大港山区的原始生态中，山高林密、溪流纵横，赋予茶叶以清幽脱俗的山野韵味。茶汤金黄透亮，轻啜一口，如沐山间清雾，花香与蜜香缠绵不绝。这片远离尘嚣的土地，孕育出了孟加拉国最富诗意的一杯红茶。',
    history: '吉大港山区是孟加拉国独特的地理单元，土著部落在此生活千年。茶园虽然开发较晚，但生态优势突出，所产红茶风格独特，近年来越来越受关注。',
    chronology: [
      { period: '古代', title: '土著部落千年茶缘', content: '吉大港山区是孟加拉国独特的地理单元，土著部落在此生活千年。' },
      { period: '当代', title: '生态优势被发掘', content: '茶园虽然开发较晚，但生态优势突出，所产红茶风格独特，近年来越来越受关注。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、地方群体种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: 'TGFOP、GFOP',
    characteristics: '条索紧细乌褐，山野花香清雅，汤色金黄明亮，滋味清甜细腻',
    tags: ['孟加拉茶', '吉大港', '山区红茶', '山野花香', '清甜', '生态茶园'],
    routes: []
  },
  {
    id: 'panchagarh-green',
    name: '班乔戈尔绿茶',
    nameEn: 'Panchagarh Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '朗布尔区',
    city: '班乔戈尔',
    description: '班乔戈尔绿茶是孟加拉国北部平原上的绿色奇迹，在这片以红茶为主的土地上独树一帜。炒青工艺赋予它清雅的栗香与甘冽的滋味，茶汤嫩绿如春日新柳。它证明了孟加拉国的风土同样能孕育出令人惊叹的绿茶佳品。',
    history: '班乔戈尔是孟加拉国最年轻的茶区之一，20世纪末才开始大规模种茶。由于地势平坦、气候特殊，这里意外地适合绿茶生产，成为孟加拉国茶叶版图上的新亮点。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: 'BT系列无性系',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级、二级',
    characteristics: '条索紧直翠绿，栗香清高持久，滋味鲜爽回甘，汤色嫩绿明亮',
    tags: ['孟加拉茶', '班乔戈尔', '绿茶', '栗香', '鲜爽', '北部平原'],
    routes: []
  },
  {
    id: 'bangladesh-white',
    name: '孟加拉白茶',
    nameEn: 'Bangladesh White Tea',
    category: '白茶',
    subCategories: ['白毫银针'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '锡尔赫特区',
    city: '斯里曼加尔',
    description: '孟加拉白茶好似热带雨林中偶然飘落的一片月光，以最温柔的工艺守护茶叶最纯净的模样。银白的芽头如针似剑，茶汤杏白澄澈，毫香轻盈如晨雾，蜜韵婉转如鸟鸣。它是孟加拉国茶人对极致品质的不懈追求，也是南亚白茶的新篇章。',
    history: '孟加拉白茶是近年才兴起的高端品类。斯里曼加尔的茶叶研究所经过多年试验，成功利用本地茶树品种制作出了媲美中国白茶的优质产品。',
    chronology: [
      { period: '当代（近年）', title: '白茶品类探索', content: '孟加拉白茶是近年才兴起的高端品类，斯里曼加尔的茶叶研究所经过多年试验，成功利用本地茶树品种制作出了媲美中国白茶的优质产品。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: 'BT系列无性系单芽',
    production: '采摘单芽、萎凋、低温干燥',
    grades: '白毫银针、特级白牡丹',
    characteristics: '芽头肥壮银白，毫香清新蜜韵悠长，汤色杏白透亮，滋味鲜醇甘甜',
    tags: ['孟加拉茶', '白茶', '白毫银针', '毫香蜜韵', '高端茶', '斯里曼加尔'],
    routes: []
  },
  {
    id: 'madhupur-tea',
    name: '马杜布尔茶',
    nameEn: 'Madhupur Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '孟加拉国',
    province: '达卡区',
    city: '马杜布尔',
    description: '马杜布尔茶产自达卡近郊的红壤丘陵，虽规模不大却品质精良，有着小家碧玉般的温婉气质。茶汤深红明亮，口感浓而不涩，带着一抹焦糖般的甜美尾韵。在这片靠近首都的土地上，茶园是城市边缘难得的绿色净土。',
    history: '马杜布尔的茶园历史可追溯至20世纪中期，是孟加拉国中部少有的产茶区。虽然产量有限，但靠近首都市场，具有独特的经济和文化意义。',
    chronology: [
      { period: '20世纪中期', title: '中部茶区开辟', content: '马杜布尔的茶园历史可追溯至20世纪中期，是孟加拉国中部少有的产茶区。' },
      { period: '当代', title: '近郊茶园意义', content: '虽然产量有限，但靠近首都市场，具有独特的经济和文化意义。' }
    ],
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、TV系列',
    production: '采摘、萎凋、揉切（CTC）、发酵、干燥',
    grades: 'BOP、BP',
    characteristics: '颗粒紧结，汤色深红，焦糖甜香，滋味浓醇回甘',
    tags: ['孟加拉茶', '马杜布尔', '红碎茶', '焦糖香', '浓醇', '近郊茶园'],
    routes: []
  }
];