window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.bhutan = [
  {
    id: 'bhutan-green',
    name: '不丹绿茶',
    nameEn: 'Bhutan Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '不丹',
    province: '萨姆奇宗',
    city: '萨姆奇',
    description: '不丹绿茶来自喜马拉雅南麓的最后香格里拉，生长在雪山融水灌溉的纯净山谷之中。炒青工艺锁住了高山春茶的鲜活，茶汤嫩绿如萨姆奇的松林晨雾，入口甘冽清甜，带着雪山与森林的空灵气息。一杯不丹绿茶，是这个幸福国度献给世界的纯净礼物。',
    history: '不丹的茶叶种植起步较晚，但喜马拉雅南麓的优越自然环境为茶树提供了得天独厚的生长条件。萨姆奇宗是不丹主要的茶叶产区，以有机种植和传统工艺著称。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种、本地群体种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索紧结翠绿，清香带山林草木气息，汤色嫩绿透亮，滋味清甜甘醇',
    tags: ['不丹茶', '喜马拉雅', '有机茶', '清甜', '纯净', '绿茶'],
    routes: []
  },
  {
    id: 'bhutan-black',
    name: '不丹红茶',
    nameEn: 'Bhutan Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '不丹',
    province: '萨姆德鲁琼卡尔宗',
    city: '萨姆德鲁琼卡尔',
    description: '不丹红茶来自东部山区的静谧茶园，在喜马拉雅的晨钟暮鼓中缓缓积累甘醇。茶汤金黄温润如佛光普照，入口醇和细腻，带着蜂蜜与熟果的甜香。在这片以国民幸福指数闻名的土地上，红茶是人与自然和谐共生的完美象征。',
    history: '萨姆德鲁琼卡尔宗位于不丹东部，是不丹最早尝试大规模种茶的地区之一。当地茶产业得到政府大力扶持，走高品质有机路线，逐渐在国际市场上崭露头角。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、不丹选育品种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级',
    characteristics: '条索紧细乌润，蜂蜜熟果甜香，汤色金黄明亮，口感醇和细腻',
    tags: ['不丹茶', '喜马拉雅', '红茶', '蜂蜜甜', '醇和', '有机'],
    routes: []
  },
  {
    id: 'bhutan-oolong',
    name: '不丹乌龙',
    nameEn: 'Bhutan Oolong Tea',
    category: '乌龙茶',
    subCategories: ['台湾乌龙'],
    continent: '亚洲',
    country: '不丹',
    province: '萨姆奇宗',
    city: '萨姆奇',
    description: '不丹乌龙是喜马拉雅高山茶园的新生之花，将台湾乌龙工艺巧妙地融入不丹纯净的风土之中。茶叶卷曲如珠，冲泡后舒展如莲，花香袅袅如寺院檀香，茶汤蜜黄澄澈如不丹的信仰之光。一杯不丹乌龙，是禅意与茶韵的完美邂逅。',
    history: '不丹近年从台湾引进乌龙茶制作技术，利用萨姆奇宗的高海拔茶园进行试制。高山的凉爽气候与充足的云雾，为乌龙茶的半发酵提供了绝佳的自然条件。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '青心乌龙、金萱',
    production: '采摘、日光萎凋、室内萎凋、摇青、杀青、揉捻、烘焙',
    grades: '特级、一级',
    characteristics: '半球形卷曲紧结，花香清雅悠长，汤色蜜黄明亮，喉韵甘醇回甘',
    tags: ['不丹茶', '乌龙茶', '喜马拉雅', '花香', '禅意', '有机'],
    routes: []
  }
];