window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.cambodia = [
  {
    id: 'mondulkiri-tea',
    name: '蒙多基里红茶',
    nameEn: 'Mondulkiri Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '柬埔寨',
    province: '蒙多基里省',
    city: '森莫诺隆',
    description: '蒙多基里红茶来自柬埔寨东部的高原秘境，茶园隐匿于茂密的热带森林与连绵的山丘之间。茶汤金黄明亮如蒙多基里的晨曦，清甜的花香与蜂蜜般的甘醇轻柔绽放。在这片人烟稀少的原野上，红茶是大自然最慷慨的恩赐，也是这片土地最纯净的表达。',
    history: '蒙多基里省是柬埔寨最偏远的省份之一，以自然生态著称。当地近年来开始发展茶叶种植，利用高海拔和原生态优势，走高品质有机红茶路线。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种、本地野生种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级',
    characteristics: '条索紧细乌润，花香蜜甜清雅，汤色金黄明亮，口感清甜柔滑',
    tags: ['柬埔寨茶', '蒙多基里', '高原红茶', '花香', '清甜', '有机'],
    routes: []
  },
  {
    id: 'kirirom-green',
    name: '基里隆绿茶',
    nameEn: 'Kirirom Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '柬埔寨',
    province: '磅士卑省',
    city: '基里隆',
    description: '基里隆绿茶取自柬埔寨最大的国家公园基里隆松林深处，清冽的山泉与高耸的松林赋予它一种洗练而纯净的气质。炒青之后茶香清新如松风，茶汤浅绿透亮，入口甘爽澄澈。在这片远离尘嚣的松林秘境中，绿茶是自然与宁静的化身。',
    history: '基里隆国家公园是柬埔寨著名的生态保护区，近年来在公园周边地区尝试茶叶种植。凉爽的微气候和洁净的环境为绿茶提供了得天独厚的条件。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '台湾绿茶品种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索紧实翠绿，松风清香淡雅，汤色浅绿明澈，滋味甘爽澄净',
    tags: ['柬埔寨茶', '基里隆', '绿茶', '松风香', '甘爽', '国家公园'],
    routes: []
  },
  {
    id: 'kampot-oolong',
    name: '贡布乌龙',
    nameEn: 'Kampot Oolong Tea',
    category: '乌龙茶',
    subCategories: ['闽南乌龙'],
    continent: '亚洲',
    country: '柬埔寨',
    province: '贡布省',
    city: '贡布',
    description: '贡布乌龙以闽南乌龙工艺为魂，以贡布山海之间的独特风土为骨，浑然天成。茶叶卷曲紧结，冲泡后花果香如贡布海风般扑面而来，茶汤金黄温润如热带夕阳。贡布不仅是世界闻名的胡椒之乡，也正在以这杯乌龙茶悄然书写柬埔寨茶文化的新篇章。',
    history: '贡布省以优质的贡布胡椒享誉世界，如今这里的茶产业也悄然兴起。茶农借鉴闽南乌龙工艺，利用贡布山海交汇的地理优势，制作出独具柬埔寨风情的乌龙茶。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '铁观音、毛蟹',
    production: '采摘、萎凋、摇青、杀青、揉捻、烘焙',
    grades: '特级、一级',
    characteristics: '条索卷曲紧结，花果香馥郁，汤色金黄明亮，滋味醇和回甘',
    tags: ['柬埔寨茶', '贡布', '乌龙茶', '花果香', '闽南工艺', '热带风情'],
    routes: []
  }
];