window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.georgia = [
  {
    id: 'ozurgeti-tea',
    name: '奥祖尔盖蒂红茶',
    nameEn: 'Ozurgeti Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '格鲁吉亚',
    province: '古里亚州',
    city: '奥祖尔盖蒂',
    description: '奥祖尔盖蒂红茶生长于格鲁吉亚西部古里亚州的青山翠谷之间，黑海湿润的风与高加索山脉的清凉交融滋养。茶汤橙红如格鲁吉亚的黄昏，入口柔滑细腻，带着淡淡的栗子甜香与野花芬芳。它是苏联时代最负盛名的茶叶产区遗珍，也是高加索大地上的红茶传奇。',
    history: '格鲁吉亚茶产业始于19世纪末，苏联时期奥祖尔盖蒂所在的古里亚州成为全苏最大的茶叶产区。虽然经历过衰退，但近年来格鲁吉亚茶业正在复苏，传统工艺重获新生。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '格鲁吉亚选育品种、中国小叶种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级、二级',
    characteristics: '条索紧细，汤色橙红明亮，栗甜花香清雅，口感柔滑细腻',
    tags: ['格鲁吉亚茶', '古里亚', '黑海', '高加索', '栗甜', '柔滑', '苏联遗珍'],
    routes: []
  },
  {
    id: 'guria-green',
    name: '古里亚绿茶',
    nameEn: 'Guria Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '格鲁吉亚',
    province: '古里亚州',
    city: '奥祖尔盖蒂',
    description: '古里亚绿茶是高加索山谷里的一抹清新生机，绿意盎然地在黑海湿润季风中轻轻摇曳。炒青工艺赋予它淡雅的豆香与清冽的甘润，茶汤如古里亚清晨的薄雾般澄澈。在高加索这片以红茶闻名的土地上，古里亚绿茶是一抹令人惊喜的亮色。',
    history: '格鲁吉亚的绿茶生产在苏联时期即有尝试，古里亚州凭借优越的自然条件成为绿茶的主要产区。当地绿茶融合了中式工艺与高加索风土，形成了独特的风格。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '格鲁吉亚本地绿茶品种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索翠绿紧结，豆香清雅带花香，汤色浅绿明亮，滋味鲜爽甘润',
    tags: ['格鲁吉亚茶', '古里亚', '绿茶', '豆香', '鲜爽', '黑海'],
    routes: []
  },
  {
    id: 'batumi-ctc',
    name: '巴统CTC红茶',
    nameEn: 'Batumi CTC Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '格鲁吉亚',
    province: '阿扎尔自治共和国',
    city: '巴统',
    description: '巴统CTC红茶来自黑海东岸的亚热带海滨，温暖湿润的气候使茶叶终年繁茂茁壮。茶汤深红浓烈如巴统港口的落日余晖，口感强劲有力，麦芽焦糖的香气直冲鼻腔。它是格鲁吉亚茶产业现代化转型的力作，为古老的茶区注入了新的活力。',
    history: '巴统是格鲁吉亚重要的港口城市，阿扎尔地区的茶叶加工在苏联时期便已规模化。CTC工艺的引入使巴统成为格鲁吉亚红碎茶的重要生产基地，产品主要出口中亚和东欧市场。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种',
    production: '采摘、萎凋、揉切（CTC）、发酵、干燥',
    grades: 'BOP、BP、Dust',
    characteristics: '颗粒均匀，汤色深红浓厚，麦芽焦糖香气突出，口感浓强刺激',
    tags: ['格鲁吉亚茶', '巴统', 'CTC', '红碎茶', '浓强', '亚热带', '黑海'],
    routes: []
  },
  {
    id: 'imereti-oolong',
    name: '伊梅列季乌龙',
    nameEn: 'Imereti Oolong Tea',
    category: '乌龙茶',
    subCategories: ['闽北乌龙'],
    continent: '亚洲',
    country: '格鲁吉亚',
    province: '伊梅列季州',
    city: '库塔伊西',
    description: '伊梅列季乌龙是高加索山脉腹地的一次大胆探索，将中国闽北乌龙工艺嫁接于格鲁吉亚的苍翠茶园。茶叶经过摇晃与氧化，绽放出蜂蜜般的甜香与熟果的馥郁，茶汤金黄温润如库塔伊西的秋日。它是格鲁吉亚茶文化创新的骄傲，也是东西方工艺交融的结晶。',
    history: '近年来格鲁吉亚茶人积极探索乌龙茶等高附加值产品，伊梅列季州率先尝试闽北乌龙工艺，利用本土原料制作出了令人惊艳的半发酵茶品。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '格鲁吉亚选育品种',
    production: '采摘、萎凋、摇青、杀青、揉捻、烘焙',
    grades: '特级、一级',
    characteristics: '条索紧结乌褐，蜂蜜甜香与熟果香交融，汤色金黄明亮，喉韵甘醇',
    tags: ['格鲁吉亚茶', '伊梅列季', '乌龙茶', '蜂蜜甜香', '创新', '高加索'],
    routes: []
  },
  {
    id: 'tbilisi-black',
    name: '第比利斯红茶',
    nameEn: 'Tbilisi Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '格鲁吉亚',
    province: '第比利斯',
    city: '第比利斯',
    description: '第比利斯红茶承载着格鲁吉亚首都的优雅与热情，在库拉河畔的丘陵茶园中精心孕育而成。茶汤橙黄如第比利斯老城的暖色石墙，入口温润如玉，带着一丝果脯般的甜香与烤面包的温暖气息。在这座有着一千五百年历史的古城里，红茶是生活、是友谊、是格鲁吉亚人待客的最高礼仪。',
    history: '第比利斯周边的茶园虽不及古里亚州广阔，但首都的消费市场和茶文化氛围浓厚。第比利斯红茶品牌将传统工艺与现代品质管理结合，代表了格鲁吉亚红茶的高端形象。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '格鲁吉亚精选品种',
    production: '采摘、萎凋、揉捻、发酵、低温干燥',
    grades: '特级、一级',
    characteristics: '条索紧秀，汤色橙黄明亮，果脯甜香带焙烤风味，口感温润醇和',
    tags: ['格鲁吉亚茶', '第比利斯', '首都茶', '果脯甜香', '温润', '高加索古城'],
    routes: []
  }
];