window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};

var worldMap = {
  '日本': 'japan',
  '印度': 'india',
  '斯里兰卡': 'sri-lanka',
  '肯尼亚': 'kenya',
  '英国': 'uk',
  '土耳其': 'turkey',
  '韩国': 'korea',
  '越南': 'vietnam',
  '印度尼西亚': 'indonesia',
  '尼泊尔': 'nepal',
  '阿根廷': 'argentina',
  '马拉维': 'malawi',
  '俄罗斯': 'russia',
  '摩洛哥': 'morocco',
  '泰国': 'thailand',
  '坦桑尼亚': 'tanzania',
  '乌干达': 'uganda',
  '卢旺达': 'rwanda',
  '缅甸': 'myanmar',
  '孟加拉国': 'bangladesh',
  '马来西亚': 'malaysia',
  '伊朗': 'iran',
  '格鲁吉亚': 'georgia',
  '阿塞拜疆': 'azerbaijan',
  '不丹': 'bhutan',
  '老挝': 'laos',
  '柬埔寨': 'cambodia',
  '菲律宾': 'philippines',
  '乌兹别克斯坦': 'uzbekistan',
  '埃塞俄比亚': 'ethiopia',
  '莫桑比克': 'mozambique',
  '津巴布韦': 'zimbabwe',
  '南非': 'south-africa',
  '布隆迪': 'burundi',
  '喀麦隆': 'cameroon',
  '刚果（金）': 'congo',
  '毛里求斯': 'mauritius',
  '尼日利亚': 'nigeria',
  '德国': 'germany',
  '法国': 'france',
  '葡萄牙': 'portugal',
  '巴西': 'brazil',
  '秘鲁': 'peru',
  '哥伦比亚': 'colombia',
  '美国': 'usa',
  '加拿大': 'canada',
  '澳大利亚': 'australia',
  '新西兰': 'new-zealand',
  '巴布亚新几内亚': 'papua-new-guinea'
};
