window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.iran = [
  {
    id: 'lahijan-tea',
    name: '拉希詹红茶',
    nameEn: 'Lahijan Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '吉兰省',
    city: '拉希詹',
    description: '拉希詹红茶如里海之滨的一抹温柔霞光，在厄尔布尔士山脉的庇护下静静生长。茶汤琥珀般澄澈温润，入口丝滑如波斯地毯的触感，带着玫瑰花瓣般的芬芳与蜂蜜的甘甜。它是伊朗茶文化的灵魂所在，每一杯都盛满了千年波斯的风雅与热情。',
    chronology: [
      { period: '19世纪末', title: '印度引种', content: '伊朗从印度引种茶树，拉希詹所在的吉兰省凭借里海沿岸的温润气候被选为首种之地，成为伊朗茶业的摇篮。' },
      { period: '20世纪', title: '茶都崛起', content: '拉希詹发展出伊朗最广阔的茶园和最具规模的茶叶加工厂，被誉为伊朗的茶都。' },
      { period: '21世纪', title: '产业成熟', content: '如今拉希詹红茶以琥珀澄澈的汤色和玫瑰花香蜜甜交融的独特风味，成为伊朗茶文化的灵魂所在。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、伊朗选育品种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级、二级',
    characteristics: '条索紧结，汤色琥珀透亮，玫瑰花香与蜜甜交融，口感丝滑醇和',
    tags: ['伊朗茶', '拉希詹', '里海', '玫瑰香', '丝滑', '茶都', '波斯风情'],
    routes: []
  },
  {
    id: 'fouman-tea',
    name: '福曼红茶',
    nameEn: 'Fouman Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '吉兰省',
    city: '福曼',
    description: '福曼红茶来自吉兰省的绿色丘陵深处，茶园被里海湿润的海风轻轻拂过，茶叶沐雨而生。茶汤金黄明亮如波斯的阳光，香气优雅悠长，入口甘醇而不失清爽。福曼的山间薄雾与肥沃红土，共同酿造了这杯柔和而富有层次的红茶佳酿。',
    chronology: [
      { period: '19世纪起', title: '传统农业重镇', content: '福曼是吉兰省历史悠久的农业重镇，茶产业与稻米、丝绸齐名，形成多元农业传统。' },
      { period: '20世纪', title: '家庭农场模式', content: '当地茶园多由小型家庭农场经营，保留了传统手工制茶技艺，品质细腻精致。' },
      { period: '21世纪', title: '精品路线', content: '福曼红茶以柔和甘醇的风味成为伊朗高端红茶的代表之一。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级',
    characteristics: '条索紧细乌褐，汤色金黄明亮，香气优雅持久，滋味甘醇清爽',
    tags: ['伊朗茶', '福曼', '里海', '传统工艺', '甘醇', '手工制茶'],
    routes: []
  },
  {
    id: 'gilani-chai',
    name: '吉兰红茶',
    nameEn: 'Gilani Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '吉兰省',
    city: '拉什特',
    description: '吉兰红茶是大批量生产的伊朗国民口粮茶，浓烈而坦荡，不矫揉不造作。茶汤深褐浓郁，入口强劲有力，带着鲜明的麦香与焦糖般的回甘。在伊朗的每一户人家、每一处茶馆，吉兰红茶是不可或缺的存在，温热着这个民族的日常与灵魂。',
    chronology: [
      { period: '20世纪', title: '省会加工中心', content: '拉什特作为吉兰省省会和经济中心，茶叶加工和贸易在此汇聚，成为伊朗茶叶产业链的核心枢纽。' },
      { period: '20世纪中后期', title: '大规模生产', content: '吉兰红茶泛指吉兰省出产的CTC和传统红碎茶，成为伊朗国内市场占有率最高的茶叶产品。' },
      { period: '21世纪', title: '国民口粮茶', content: '吉兰红茶以浓烈坦荡的风味成为伊朗每户人家不可或缺的存在，温热着这个民族的日常与灵魂。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、本地混合种',
    production: '采摘、萎凋、揉切、发酵、干燥',
    grades: 'BOP、BP、Dust',
    characteristics: '颗粒匀整，汤色深褐浓郁，麦香焦糖香突出，滋味浓烈回甘',
    tags: ['伊朗茶', '吉兰', '国民茶', '浓烈', '麦香', '日常必备'],
    routes: []
  },
  {
    id: 'langarud-tea',
    name: '兰加鲁德茶',
    nameEn: 'Langarud Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '吉兰省',
    city: '兰加鲁德',
    description: '兰加鲁德茶被誉为里海沿岸的珍珠，茶叶在温润的海风中缓慢成熟，积淀出丰富的内含物质。茶汤橙红清澈如波斯琉璃，花香与果香交织，口感温润如玉，回甘如泉涌般绵长。每一片兰加鲁德茶叶都是大自然赐予吉兰大地的慷慨馈赠。',
    chronology: [
      { period: '19世纪末起', title: '东部茶区发展', content: '兰加鲁德位于吉兰省东部，是伊朗重要的茶叶种植区，茶园得益于里海的温和气候和充沛降水。' },
      { period: '20世纪', title: '高端路线确立', content: '兰加鲁德茶叶以柔和甜润的品质著称，逐步确立为伊朗高端红茶的代表产区之一。' },
      { period: '21世纪', title: '里海珍珠', content: '兰加鲁德茶以花果香馥郁和温润回甘绵长的卓越品质被誉为"里海沿岸的珍珠"。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '伊朗选育优质品种',
    production: '采摘、萎凋、揉捻、发酵、低温干燥',
    grades: '特级、一级',
    characteristics: '条索紧秀，汤色橙红清澈，花果香馥郁，口感温润回甘绵长',
    tags: ['伊朗茶', '兰加鲁德', '高端红茶', '花果香', '温润', '里海珍珠'],
    routes: []
  },
  {
    id: 'gorgan-black',
    name: '戈尔甘红茶',
    nameEn: 'Gorgan Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '戈勒斯坦省',
    city: '戈尔甘',
    description: '戈勒斯坦红茶扎根于里海东岸的冲积平原，充沛的日照与肥沃的土壤赋予它奔放而热烈的性格。茶汤深红如戈勒斯坦的落日，口感浓稠饱满，带着泥土的质朴香气与焦糖般的厚重甜感。在这片古老的土地上，红茶是游牧与农耕文明交融的见证。',
    chronology: [
      { period: '20世纪末', title: '新兴茶区', content: '戈勒斯坦省虽不如吉兰省历史悠久，但凭借里海东岸冲积平原的优越自然条件发展迅速。' },
      { period: '21世纪初', title: 'CTC规模化', content: '当地建立CTC生产线为伊朗国内市场提供大量优质红碎茶，成为伊朗北部重要茶叶供应基地。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种',
    production: '采摘、萎凋、揉切、发酵、干燥',
    grades: 'BOP、BP',
    characteristics: '颗粒紧实，汤色深红浓稠，焦糖甜香厚重，口感浓烈饱满',
    tags: ['伊朗茶', '戈勒斯坦', '红碎茶', '浓烈', '焦糖', '里海东岸'],
    routes: []
  },
  {
    id: 'shirvan-black',
    name: '希尔凡红茶',
    nameEn: 'Shirvan Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '北呼罗珊省',
    city: '希尔凡',
    description: '希尔凡红茶来自伊朗东北部的呼罗珊大地，在这片曾经的丝绸之路上，茶叶汲取了高原的辽阔与大漠的苍茫。茶汤橙黄透亮，香气沉稳而深邃，口感醇厚如山石。一杯希尔凡红茶，是呼罗珊大地千年历史的浓缩，带着丝路驼铃的悠远回响。',
    chronology: [
      { period: '21世纪初', title: '新兴高原茶区', content: '北呼罗珊省是伊朗新兴的茶区，希尔凡地区利用高原气候和充足日照开辟了茶园。' },
      { period: '近年', title: '逐步获认可', content: '希尔凡红茶带有独特的高原风味，沉稳醇厚的风格正在逐步获得国内消费者认可。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、高原适应性品种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '一级、二级',
    characteristics: '条索紧实，汤色橙黄透亮，沉稳木质香调，口感醇厚扎实',
    tags: ['伊朗茶', '希尔凡', '呼罗珊', '高原红茶', '沉稳', '醇厚'],
    routes: []
  },
  {
    id: 'tonkabon-green',
    name: '通卡邦绿茶',
    nameEn: 'Tonkabon Green Tea',
    category: '绿茶',
    subCategories: ['蒸青绿茶'],
    continent: '亚洲',
    country: '伊朗',
    province: '马赞德兰省',
    city: '通卡邦',
    description: '通卡邦绿茶是伊朗茶苑中的一朵素净之花，以日本蒸青工艺锁住里海之春的鲜嫩翠色。茶汤碧绿澄澈如马赞德兰森林中的泉水，海藻般的鲜香与清甜交织，令人心旷神怡。在这红茶为尊的国度，通卡邦绿茶独辟蹊径，展现出伊朗茶的多元可能。',
    chronology: [
      { period: '21世纪初', title: '差异化创新', content: '通卡邦位于马赞德兰省西部靠近里海，当地近年引进日本蒸青技术制作绿茶。' },
      { period: '近年', title: '开辟新天地', content: '以日本蒸青工艺锁住里海之春的鲜嫩翠色，在伊朗红茶主导的市场中以差异化路线开辟了一片新天地。' },
    ],
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '薮北种、伊朗本土绿茶品种',
    production: '采摘、蒸青、冷却、揉捻、干燥',
    grades: '特级、一级',
    characteristics: '条索翠绿紧直，海藻鲜香清新，汤色碧绿透亮，滋味鲜醇甘甜',
    tags: ['伊朗茶', '通卡邦', '蒸青绿茶', '鲜爽', '海苔香', '里海', '创新'],
    routes: []
  }
];