window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.malaysia = [
  {
    id: 'cameron-highlands-tea',
    name: '金马仑高原红茶',
    nameEn: 'Cameron Highlands Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '彭亨州',
    city: '金马仑高原',
    description: '金马仑高原红茶的茶园蜿蜒于海拔一千五百米的青翠山峦间，终年云雾缭绕、气候凉爽如永恒的春天。茶汤橙红透亮如高原夕阳，入口柔滑醇和，花果香与蜜甜在唇齿间层层绽放。这片马来西亚最著名的茶乡，将英式下午茶的优雅完美融入了热带风情。',
    history: '金马仑高原的茶产业始于1929年，英国殖民者将茶树引入这片凉爽的高地。经过近百年发展，这里已成为东南亚规模最大、风景最美的茶园观光胜地。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、台湾青心',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: 'OP、BOP、FOP',
    characteristics: '条索紧结乌润，花果香清雅，汤色橙红明亮，口感柔滑甘醇',
    tags: ['马来西亚茶', '金马仑高原', '工夫红茶', '花果香', '柔滑', '高原茶园', '百年历史'],
    routes: []
  },
  {
    id: 'sabah-tea',
    name: '沙巴红茶',
    nameEn: 'Sabah Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '沙巴州',
    city: '兰瑙',
    description: '沙巴红茶生长于婆罗洲神山脚下的火山沃土之上，被热带雨林的灵气与高山云雾日夜浸润。茶汤金黄明亮，入口清甜温润，带着一抹仿佛原始森林般的纯净气息。在这片生态净土上，每一片茶叶都诉说着婆罗洲与世无争的自然之美。',
    history: '沙巴茶业始于20世纪70年代，兰瑙地区的茶园坐落在京那巴鲁山脚下，海拔适中、土壤肥沃。沙巴茶以有机种植著称，是马来西亚品质最纯净的茶叶之一。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: 'OP、BOP',
    characteristics: '条索紧细，汤色金黄透亮，清香纯净带蜜甜，口感细腻回甘',
    tags: ['马来西亚茶', '沙巴', '婆罗洲', '有机茶', '纯净', '清甜', '神山'],
    routes: []
  },
  {
    id: 'boh-golden',
    name: '宝乐金毫茶',
    nameEn: 'BOH Golden Tips Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '彭亨州',
    city: '金马仑高原',
    description: '宝乐金毫茶是马来西亚金马仑高原上的璀璨明珠，精挑细采的金黄色芽尖在杯中摇曳生姿。茶汤金圈明亮，香气馥郁如山花烂漫，口感醇厚中透着丝绸般的柔滑质感。它是宝乐茶园献给世界的最高礼赞，也是马来西亚茶工艺的巅峰之作。',
    history: 'BOH茶园是马来西亚最大的茶叶生产企业，创立于1929年。金毫茶是其高端产品线，精选最优质的嫩芽精制而成，代表了马来西亚红茶的顶级水准。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种金芽品系',
    production: '采摘嫩芽、萎凋、轻揉、发酵、低温慢烘',
    grades: '金毫特级、金毫一级',
    characteristics: '金毫满披，香气馥郁持久，汤色金圈红艳，滋味醇厚丝滑，叶底红匀柔软',
    tags: ['马来西亚茶', '宝乐', '金毫', '金马仑', '高端红茶', '醇厚丝滑', '芽尖茶'],
    routes: []
  },
  {
    id: 'teh-tarik',
    name: '印度拉茶',
    nameEn: 'Teh Tarik',
    category: '调味茶',
    subCategories: ['调味红茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '吉隆坡',
    city: '吉隆坡',
    description: '印度拉茶虽源自南亚，却在马来西亚的土地上淬炼出属于自己的灵魂。滚烫的红茶与炼乳在高空反复拉制，泡沫绵密如云，茶香与奶香在反复冲击中融为一体。一杯地道的拉茶，是马来西亚街头最鲜活的文化符号，浓香甜滑，令人上瘾。',
    history: '拉茶随印度移民传入马来半岛，经过数十年的本土化演变，已成为马来西亚国民饮品。在吉隆坡的嘛嘛档里，拉茶师傅的表演本身就是一门艺术。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: 'CTC红碎茶',
    production: '冲泡浓茶、加入炼乳与香料、反复高空拉制起泡',
    grades: '普通拉茶、香料拉茶',
    characteristics: '泡沫细腻绵密，茶奶融合香浓，口感甜滑醇厚如丝绸',
    tags: ['马来西亚茶', '拉茶', '国民饮品', '街头美食', '浓香', '甜滑', '文化符号'],
    routes: []
  },
  {
    id: 'borneo-green',
    name: '婆罗洲绿茶',
    nameEn: 'Borneo Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '沙捞越州',
    city: '古晋',
    description: '婆罗洲绿茶汲取了沙捞越热带雨林深处的纯净精华，清新如雨后森林的第一缕阳光。炒青工艺赋予它轻盈的豆香与甘冽的滋味，茶汤浅绿透亮如猫城古晋的晨光。在这片犀鸟翱翔的土地上，一杯绿茶是对自然最虔诚的致敬。',
    history: '沙捞越的茶叶种植起步较晚，但热带雨林气候和肥沃的土壤为绿茶提供了绝佳的生长环境。当地茶农结合传统工艺，打造出了风格清新的婆罗洲绿茶。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '台湾青心乌龙、阿萨姆种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索紧结翠绿，豆香清新带花香，汤色浅绿明亮，滋味甘冽回甜',
    tags: ['马来西亚茶', '沙捞越', '绿茶', '婆罗洲', '清新', '甘冽', '热带雨林'],
    routes: []
  },
  {
    id: 'genting-oolong',
    name: '云顶乌龙',
    nameEn: 'Genting Oolong Tea',
    category: '乌龙茶',
    subCategories: ['台湾乌龙'],
    continent: '亚洲',
    country: '马来西亚',
    province: '彭亨州',
    city: '金马仑高原',
    description: '云顶乌龙出自金马仑高原的高海拔茶园，融合了台湾制茶技艺与马来西亚的独特风土。茶叶呈半球形卷曲，冲泡后舒展如花绽放，花香与果香交织升腾。茶汤金黄明澈，入口甘醇滑润，喉韵悠长如高原的薄雾不散。',
    history: '金马仑高原的乌龙茶制作始于台湾茶人的技术引进，利用高海拔凉爽气候，成功复刻了台湾高山乌龙的风格，成为马来西亚茶产业的一大创新。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '青心乌龙、金萱',
    production: '采摘、日光萎凋、室内萎凋、摇青、杀青、揉捻、烘焙',
    grades: '特级、一级',
    characteristics: '半球形紧结墨绿，花香果香交融，汤色金黄明亮，喉韵甘醇悠长',
    tags: ['马来西亚茶', '云顶乌龙', '金马仑', '花香', '果香', '喉韵', '台式乌龙'],
    routes: []
  },
  {
    id: 'malacca-tea',
    name: '马六甲茶',
    nameEn: 'Malacca Black Tea',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '马六甲州',
    city: '马六甲',
    description: '马六甲茶带着古城六百年的历史沉香，将多元文化交融的气息融入每一杯红茶之中。茶汤深红厚重，口感浓郁强劲，隐约透出香料般的复杂风味。在马六甲河畔的老街茶馆里，一杯红茶便是对这座世界文化遗产城市最深情的品味。',
    history: '马六甲的茶文化深受中国、葡萄牙、荷兰、英国等多重殖民历史影响，形成了独特的混合风格。当地的茶品牌将这份历史底蕴注入产品之中。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、CTC混合',
    production: '采摘、萎凋、揉切、发酵、干燥',
    grades: 'BOP、BP',
    characteristics: '颗粒紧实，汤色深红厚重，香气复合带香料韵味，口感浓郁强劲',
    tags: ['马来西亚茶', '马六甲', '红碎茶', '古城', '浓郁', '香料韵味', '历史文化'],
    routes: []
  },
  {
    id: 'perlis-green',
    name: '玻璃市绿茶',
    nameEn: 'Perlis Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '马来西亚',
    province: '玻璃市州',
    city: '加央',
    description: '玻璃市绿茶来自马来西亚最小的州，却独具一份北方边境的宁静与纯粹。热带阳光与石灰岩山丘的独特风土，赋予它清爽宜人的口感与淡雅的草木芬芳。茶汤嫩绿清澈，入口甘润如玻璃市稻田里吹来的微风，洗去一身燥热。',
    history: '玻璃市州的茶叶种植属于马来西亚的新兴产茶尝试，利用当地独特的石灰岩地貌和充足的阳光，探索绿茶在本土的适应性，为北部农业发展开辟了新路。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '台湾绿茶品种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索紧实翠绿，草木清香淡雅，汤色嫩绿明亮，滋味清爽甘润',
    tags: ['马来西亚茶', '玻璃市', '绿茶', '清爽', '草木香', '北部茶区'],
    routes: []
  }
];