window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.myanmar = [
  {
    id: 'shan-tea',
    name: '掸邦茶',
    nameEn: 'Shan Tea',
    category: '绿茶',
    subCategories: ['晒青绿茶'],
    continent: '亚洲',
    country: '缅甸',
    province: '掸邦',
    city: '东枝',
    description: '掸邦茶生长于缅甸东部高原云雾缭绕的群山中，日光萎凋赋予其清冽而温润的独特气韵。茶汤澄澈如高原秋露，入口甘醇，带着淡淡的花蜜香与草木的清芬。它是掸邦人民日常生活中不可或缺的陪伴，也是缅甸最具代表性的绿茶之一。',
    history: '掸邦的茶树种植历史可溯至数百年前，当地少数民族世代以茶为生，茶早已融入他们的血脉与信仰。掸邦高原得天独厚的自然条件，使这里成为缅甸最重要的产茶区之一。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '云南大叶种',
    production: '采摘、萎凋、杀青、揉捻、日晒干燥',
    grades: '特级、一级、二级',
    characteristics: '汤色黄绿明亮，香气清雅带花果香，滋味鲜醇回甘，叶底嫩绿匀整',
    tags: ['缅甸茶', '掸邦', '晒青', '高原茶', '花蜜香', '清冽甘醇', '传统工艺'],
    routes: []
  },
  {
    id: 'palaung-tea',
    name: '崩龙茶',
    nameEn: 'Palaung Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '缅甸',
    province: '掸邦',
    city: '昔卜',
    description: '崩龙茶出自德昂族茶农的巧手，将古老民族的制茶智慧凝结于每一片嫩叶之中。高温杀青锁住了春山的翠意，茶香浓郁而沉稳，滋味醇厚如山民的性情。一杯崩龙茶，是掸北山林最质朴的表达。',
    history: '崩龙族（德昂族）是缅甸古老的种茶民族之一，他们视茶树为上天赐予的神树，千百年来在昔卜山间精耕细作。崩龙茶承载着这个民族与自然共生的悠远记忆。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '云南大叶种、崩龙群体种',
    production: '采摘、摊晾、高温杀青、揉捻、炒干',
    grades: '特级、一级、二级',
    characteristics: '条索紧结墨绿，香气栗香持久，滋味浓厚回甘，汤色嫩绿透亮',
    tags: ['缅甸茶', '崩龙茶', '炒青', '德昂族', '栗香', '浓厚回甘', '传统工艺'],
    routes: []
  },
  {
    id: 'wa-tea',
    name: '佤山古树茶',
    nameEn: 'Wa Ancient Tree Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '缅甸',
    province: '掸邦',
    city: '邦康',
    description: '佤山古树茶采自中缅边境原始森林中的百年古茶树，每一片茶叶都饱含岁月的沉淀与山野的灵气。发酵后的茶汤红艳如落日熔金，蜜糖般的甜香与木质调的醇厚交织缠绕。啜饮之间，仿佛能听见佤山深处的风声与鸟鸣。',
    history: '佤邦山区自古野生茶树遍布，佤族先民很早便懂得采制茶叶用于祭祀和药用。古树茶资源丰富，近年才被外界所识，成为缅甸红茶中的一颗璀璨明珠。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '古树野生大叶种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '古树单株、古树混采、一级',
    characteristics: '汤色红艳明亮，蜜糖香与木质香交融，滋味甜醇饱满，叶底红褐肥厚',
    tags: ['缅甸茶', '佤邦', '古树红茶', '蜜糖香', '甜醇', '百年古树', '山野气韵'],
    routes: []
  },
  {
    id: 'laphet',
    name: '缅甸腌茶',
    nameEn: 'Laphet (Burmese Fermented Tea)',
    category: '代茶类',
    subCategories: ['花草代茶'],
    continent: '亚洲',
    country: '缅甸',
    province: '掸邦',
    city: '景栋',
    description: '缅甸腌茶是举世无双的食茶珍品，将鲜叶蒸制后密封发酵，化作酸香浓郁、微苦回甘的独特风味。它不拘泥于冲泡饮用，而是作为凉拌菜肴登上餐桌，佐以蒜、辣椒、花生，成为缅甸人待客的最高礼遇。一口腌茶沙拉，酸甜苦辣俱陈，恍若人生百味。',
    history: '腌茶文化是缅甸独有的饮食传统，据说起源于古代茶马古道上的物资保存智慧。景栋地区至今保留着最传统的腌茶手工艺，代代传承，成为缅甸文化遗产的活态见证。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '云南大叶种',
    production: '采摘、蒸青、揉捻、密封发酵、腌制熟成',
    grades: '手工腌茶、机制腌茶',
    characteristics: '茶底酸香醇厚，口感软韧微苦，佐以调料风味层次丰富',
    tags: ['缅甸茶', '腌茶', '食茶', '发酵', '酸香', '文化遗产', '茶沙拉'],
    routes: []
  },
  {
    id: 'mandalay-green',
    name: '曼德勒绿茶',
    nameEn: 'Mandalay Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '缅甸',
    province: '曼德勒省',
    city: '曼德勒',
    description: '曼德勒绿茶带着古都的温雅气质，在热带季风的吹拂下孕育出别样的清丽。炒青工艺赋予它淡雅的豆香与柔和的口感，茶汤浅黄如初春的日光。在伊洛瓦底江畔的茶馆里，一杯曼德勒绿茶便是缅甸慢生活的最佳注脚。',
    history: '曼德勒作为缅甸最后的王朝古都，茶文化在此地深深扎根。英殖民时期后，曼德勒周边开始引种茶树，逐步发展成为缅甸中部重要的绿茶产地。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级、二级',
    characteristics: '条索紧细，豆香清雅，滋味柔和甘润，汤色浅黄明亮',
    tags: ['缅甸茶', '曼德勒', '炒青', '豆香', '古都', '柔和甘润'],
    routes: []
  },
  {
    id: 'pyin-oo-lwin-tea',
    name: '彬乌伦红茶',
    nameEn: 'Pyin Oo Lwin Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '缅甸',
    province: '曼德勒省',
    city: '彬乌伦',
    description: '彬乌伦茶园坐落在海拔千米的山间避暑胜地，凉爽气候赋予红茶以细腻的层次与优雅的花果香。茶汤橙红透亮，入口丝滑，尾韵带着一丝英式下午茶的古典风情。这座殖民时期的花园城市，用它独特的方式讲述着缅甸红茶的故事。',
    history: '彬乌伦（眉谬）在英国殖民时期是避暑胜地，英国人将茶树引种至此，开启了缅甸现代茶产业的先河。百年过去，彬乌伦的红茶依然保留着那份独特的英伦遗韵。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆种、锡兰种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: 'OP、BOP、FOP',
    characteristics: '汤色橙红透亮，花果香优雅，口感丝滑细腻，回甘清甜持久',
    tags: ['缅甸茶', '彬乌伦', '工夫红茶', '花果香', '丝滑', '英伦遗韵', '高山红茶'],
    routes: []
  },
  {
    id: 'kachin-white',
    name: '克钦白茶',
    nameEn: 'Kachin White Tea',
    category: '白茶',
    subCategories: ['白牡丹'],
    continent: '亚洲',
    country: '缅甸',
    province: '克钦邦',
    city: '密支那',
    description: '克钦白茶采撷于缅北雪山融水滋养的高山茶园，以最简朴的工艺守住茶叶天然的本真。白毫满披如冬日初雪，茶汤杏白清透，毫香与野花蜜香袅袅升起。身处克钦邦的苍茫群山之间，一杯白茶足以涤荡尘心，返璞归真。',
    history: '克钦邦地处缅北高海拔山区，气候寒凉，非常适合白茶的制作。当地茶农借鉴了中国云南白茶的制作技艺，结合本土原料，发展出了独具特色的克钦白茶。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '云南大叶种、克钦群体种',
    production: '采摘、萎凋、干燥',
    grades: '白牡丹、一级、二级',
    characteristics: '芽叶连枝白毫显露，毫香清雅带蜜韵，滋味鲜爽甘甜，汤色杏白透亮',
    tags: ['缅甸茶', '克钦', '白茶', '白牡丹', '毫香', '鲜爽甘甜', '高山茶'],
    routes: []
  }
];