window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.philippines = [
  {
    id: 'benguet-tea',
    name: '本格特茶',
    nameEn: 'Benguet Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '菲律宾',
    province: '本格特省',
    city: '碧瑶',
    description: '本格特茶生长于菲律宾夏都碧瑶的高山之上，科迪勒拉山脉的清凉云雾日夜滋养着这片茶园。炒青之后茶香清幽如松间晓风，茶汤嫩绿透亮如碧瑶山间的清泉，入口甘爽鲜醇。它是菲律宾最负盛名的本土茶品，也是吕宋高原献给世界的清新问候。',
    history: '本格特省的茶叶种植始于20世纪初的美国殖民时期，碧瑶市周边的凉爽山地气候非常适宜茶树生长。经过百年发展，本格特茶已成为菲律宾茶文化的象征。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '中国小叶种、阿萨姆杂交种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级、二级',
    characteristics: '条索紧细翠绿，松风清香淡雅，汤色嫩绿透亮，滋味鲜醇甘爽',
    tags: ['菲律宾茶', '本格特', '碧瑶', '绿茶', '高山茶', '松风香', '鲜醇'],
    routes: []
  },
  {
    id: 'sagada-green',
    name: '萨加达绿茶',
    nameEn: 'Sagada Green Tea',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '菲律宾',
    province: '高山省',
    city: '萨加达',
    description: '萨加达绿茶来自科迪勒拉深山中的秘境小镇，茶园与古老的悬棺和梯田共存，浸润了千年的山野灵气。炒青工艺锁住了高山云雾的鲜嫩，茶汤碧绿明澈，豆香与草木清香交织萦绕。一杯萨加达绿茶，是菲律宾山地民族与自然万物的心灵对话。',
    history: '萨加达是高山省的一个神秘小镇，以悬棺和洞穴闻名。当地的茶园虽规模不大，但自然环境极为优越，海拔高、云雾多，生产出的绿茶品质纯净而独特。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '中国小叶种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级',
    characteristics: '条索紧结深绿，豆香与草木清香，汤色碧绿明澈，滋味甘甜清醇',
    tags: ['菲律宾茶', '萨加达', '高山茶', '豆香', '秘境', '绿茶'],
    routes: []
  },
  {
    id: 'bukidnon-black',
    name: '布基农红茶',
    nameEn: 'Bukidnon Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '菲律宾',
    province: '布基农省',
    city: '马来巴来',
    description: '布基农红茶来自菲律宾南部棉兰老岛的高原中心，热带阳光与凉爽山风交替塑造了它独特的个性。茶汤橙红明亮如布基农草原的黄昏，果香与焦糖甜香温暖而丰饶，口感醇厚甘润。在菲律宾这片以绿茶为主的土地上，布基农红茶是一抹温暖而明亮的异彩。',
    history: '布基农省位于棉兰老岛内陆高原，是菲律宾新兴的茶叶产区。当地利用高海拔的凉爽气候尝试红茶制作，成功开拓了菲律宾本土红茶的市场。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级',
    characteristics: '条索紧实乌润，果香焦糖甜香交融，汤色橙红明亮，口感醇厚甘润',
    tags: ['菲律宾茶', '布基农', '棉兰老', '红茶', '果香', '焦糖甜', '高原'],
    routes: []
  }
];