window.TeaData = window.TeaData || {};
window.TeaData.world = window.TeaData.world || {};
window.TeaData.world.uzbekistan = [
  {
    id: 'kok-choy',
    name: '乌兹别克绿茶',
    nameEn: 'Kok Choy (Uzbek Green Tea)',
    category: '绿茶',
    subCategories: ['炒青绿茶'],
    continent: '亚洲',
    country: '乌兹别克斯坦',
    province: '塔什干州',
    city: '塔什干',
    description: '乌兹别克绿茶（科克茶）是中亚茶文化的绿色灵魂，在塔什干周边的山谷中迎着天山融雪静静生长。茶汤浅绿澄澈如费尔干纳的春日晴空，入口甘冽清爽，带着草木的清芬与一丝薄荷般的凉意。在这片丝路古道上，绿茶是乌兹别克人三百六十五天从不缺席的生命之水。',
    history: '乌兹别克斯坦的茶文化深受丝绸之路影响，虽然大部分茶叶靠进口，但塔什干州近年不断尝试本土茶树种植。科克茶（绿茶的乌兹别克语）是当地人最日常的饮品，配以馕和干果，是乌兹别克待客之道的核心。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '中国小叶种、本地适应性品种',
    production: '采摘、摊晾、杀青、揉捻、炒干',
    grades: '特级、一级、二级',
    characteristics: '条索紧结翠绿，草木清香淡雅，汤色浅绿明亮，滋味甘冽清爽',
    tags: ['乌兹别克茶', '塔什干', '绿茶', '丝路', '甘冽', '日常必备'],
    routes: []
  },
  {
    id: 'qora-choy',
    name: '乌兹别克红茶',
    nameEn: 'Qora Choy (Uzbek Black Tea)',
    category: '红茶',
    subCategories: ['红碎茶'],
    continent: '亚洲',
    country: '乌兹别克斯坦',
    province: '撒马尔罕州',
    city: '撒马尔罕',
    description: '乌兹别克红茶（科拉茶）承载着撒马尔罕千年古城的厚重与辉煌，在帖木儿帝国的故都浸润了历史的沉香。茶汤深红浓郁如撒马尔罕的古老砖墙，口感强劲有力，麦芽的甜香与一丝胡椒般的辛香交织缠绕。在蓝色穹顶与金色阳光之下，红茶是丝路遗韵与中亚热情的交融。',
    history: '撒马尔罕是丝绸之路上的明珠城市，茶文化在此积淀深厚。乌兹别克红茶（科拉茶）是当地人冬日和节庆时的重要饮品，常与香料共煮，形成独具中亚风情的红茶习俗。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: 'CTC进口原料、本地加工',
    production: '采摘、萎凋、揉切、发酵、干燥',
    grades: 'BOP、BP',
    characteristics: '颗粒紧实，汤色深红浓郁，麦芽辛香交织，口感强劲醇厚',
    tags: ['乌兹别克茶', '撒马尔罕', '红茶', '丝路', '强劲', '古城'],
    routes: []
  },
  {
    id: 'fergana-tea',
    name: '费尔干纳红茶',
    nameEn: 'Fergana Black Tea',
    category: '红茶',
    subCategories: ['工夫红茶'],
    continent: '亚洲',
    country: '乌兹别克斯坦',
    province: '费尔干纳州',
    city: '浩罕',
    description: '费尔干纳红茶来自乌兹别克斯坦最富饶的费尔干纳谷地，天山和帕米尔的高山融雪滋养着这片沃土。茶汤金黄温润如浩罕可汗宫殿的琉璃灯光，花香与蜜甜层层舒展，口感醇和细腻。昔日浩罕汗国的王公贵族便以茶待客，如今这杯红茶依然延续着中亚大地的热情与慷慨。',
    history: '费尔干纳谷地是乌兹别克斯坦的农业核心区，浩罕古城曾是浩罕汗国的首都。当地近年在小规模茶园中尝试工夫红茶制作，以高品质路线致敬这片土地的深厚历史。',
    historyDetail: '',
    legends: '',
    originDetail: '',
    cultivars: '阿萨姆杂交种',
    production: '采摘、萎凋、揉捻、发酵、干燥',
    grades: '特级、一级',
    characteristics: '条索紧细，花香蜜甜清雅，汤色金黄明亮，口感醇和细腻',
    tags: ['乌兹别克茶', '费尔干纳', '浩罕', '红茶', '花香', '蜜甜', '丝路古国'],
    routes: []
  }
];