window.TeaData = window.TeaData || {};
window.TeaData.teahouse = window.TeaData.teahouse || {};

window.TeaData.teahouse.americas = [
  {
    id: 'portland-japanese-garden-tea-house',
    name: '波特兰日本茶园茶室',
    nameEn: 'Tea House at Japanese Garden',
    continent: '北美洲',
    country: '美国',
    province: '俄勒冈州',
    city: '波特兰',
    address: '波特兰华盛顿公园',
    established: '1967年',
    style: '日式茶园茶室',
    specialty: '日式抹茶、煎茶、茶道体验',
    highlight: '美国最著名的日本茶园茶室，每年举办传统茶道表演',
    imageIcon: '🌳',
    color: '#2E7D32',
    description: '波特兰日本茶园茶室位于俄勒冈州波特兰的华盛顿公园内，是美国最著名的日式茶园之一。这座茶园建于1967年，完全复刻了京都的传统日式园林风格——枯山水、石灯笼、竹篱笆、茶庭小径，茶室本身也是一座纯正的日本传统建筑。茶园每年举办多次传统茶道表演，是北美地区日本茶文化传播的重要基地。',
    teas: ['matcha','sencha','gyokuro','hojicha','genmaicha'],
    tags: ['波特兰','日本茶园','茶道','华盛顿公园','俄勒冈','日式茶室'],
    chronology: [
      { period: '1963-1967年', title: '茶园创建', content: '1963年波特兰市与日本京都市结为友好城市，作为文化交流项目，1967年在华盛顿公园内建成了这座日本茶园和配套的茶室。茶室完全由日本工匠建造，建筑材料大部分从日本运来。' },
      { period: '1967-1990年', title: '早期发展', content: '1967年至1990年代，茶园逐步完善，茶室开始定期举办茶道表演，由从日本请来的茶道老师主持。这一时期，波特兰日本茶园成为北美日本文化爱好者的朝圣之地。' },
      { period: '1990-2010年', title: '翻新扩建', content: '1990年代和2000年代，茶园进行了两次大规模翻新，茶室也进行了全面修缮，增加了更多的体验项目——如茶道入门课程、和服体验、和果子制作等。' },
      { period: '2010年至今', title: '当代茶旅地标', content: '2010年以来，波特兰日本茶园已成为俄勒冈州排名第一的旅游景点，每年接待游客超过50万人次，茶室已成为北美日本茶道体验的最佳场所之一。' }
    ]
  },
  {
    id: 'tea-sympathy',
    name: '同情茶室',
    nameEn: 'Tea & Sympathy',
    continent: '北美洲',
    country: '美国',
    province: '纽约州',
    city: '纽约',
    address: '格林威治村',
    established: '1990年代',
    style: '英式茶室',
    specialty: '英式下午茶、司康饼、英国茶',
    highlight: '纽约最著名的英式茶室，格林威治村的标志性咖啡馆',
    imageIcon: '🇬🇧',
    color: '#C62828',
    description: 'Tea & Sympathy（同情茶室）位于纽约格林威治村，是这座城市最著名的英式茶室。自1990年代开业以来，它以地道的英式下午茶、司康饼和舒适的家庭氛围，成为纽约人和游客的最爱。茶室由英国移民Nicky Perry创立，初衷是为纽约的英国社区提供家的味道——如今，这里已成为纽约英式文化的地标。',
    teas: ['earl-grey','darjeeling','ceylon','assam','english-breakfast'],
    tags: ['纽约','格林威治村','英式茶室','司康饼','英国茶','纽约地标'],
    chronology: [
      { period: '1990年代初', title: '初创时期', content: '1990年代初，来自英国的Nicky Perry在格林威治村开设了Tea & Sympathy，初衷是为纽约的英国社区提供一个感受家乡味道的地方——提供正宗的英式早餐、下午茶和司康饼。' },
      { period: '1990-2000年', title: '格林威治村地标', content: '1990年代，随着格林威治村成为纽约文化中心，Tea & Sympathy也成为了文化名人、艺术家和作家常去的地方——在这里可以偶遇无数文艺界名人。' },
      { period: '2000-2020年', title: '旅游打卡地', content: '2000年代起，Tea & Sympathy被无数旅游攻略和媒体报道，成为纽约英式下午茶的代名词，每年接待游客数十万人次。' },
      { period: '2020年至今', title: '疫情后的坚守', content: '2020年疫情期间，Tea & Sympathy通过外卖和社区支持度过了难关，如今继续在格林威治村为纽约人提供地道的英式味道。' }
    ]
  },
  {
    id: 'dobrada-tea',
    name: '多布拉达茶室',
    nameEn: 'Dobrada Tea',
    continent: '北美洲',
    country: '美国',
    province: '佛蒙特州',
    city: '伯灵顿',
    address: '教堂街',
    established: '2005年',
    style: '波西米亚风格茶室',
    specialty: '世界各地茶叶、草本茶、素食茶点',
    highlight: '来自捷克布拉格的波西米亚风格茶室，佛蒙特州最著名的茶馆',
    imageIcon: '🍵',
    color: '#8E24AA',
    description: 'Dobrada Tea（多布拉达茶室）位于佛蒙特州伯灵顿市中心教堂街，是一家由捷克移民创立的波西米亚风格茶室。“Dobrada”在捷克语中意为“好茶”，这里供应来自世界各地的茶叶——中国、日本、印度、斯里兰卡、捷克本地草药茶等。茶室内部装饰充满波西米亚气息，是伯灵顿最受欢迎的休闲社交场所之一。',
    teas: ['earl-grey','sencha','matcha','darjeeling','ceylon','moroccan-mint'],
    tags: ['伯灵顿','佛蒙特','波西米亚','世界茶','捷克','教堂街'],
    chronology: [
      { period: '2000-2005年', title: '筹备与创立', content: '2000年代初，来自捷克布拉格的移民在伯灵顿定居，发现这座新英格兰城市缺少一个多元文化的茶馆。2005年，他们在教堂街开设了Dobrada Tea，希望将布拉格的波西米亚茶室文化带到美国。' },
      { period: '2005-2015年', title: '伯灵顿地标', content: '2005年至2015年，Dobrada Tea迅速成为伯灵顿文化生活的一部分——作家在这里写作，学生在这里聚会，游客在这里体验世界各地的茶叶。' },
      { period: '2015-2020年', title: '扩张与创新', content: '2010年代后期，Dobrada Tea推出了线上茶叶销售业务，并创新了多种茶调饮品和茶甜点，吸引了更多年轻顾客。' },
      { period: '2020年至今', title: '社区中心', content: '2020年疫情期间，Dobrada Tea通过社区支持和外卖度过了难关，如今不仅是一家茶馆，更成为伯灵顿社区的重要文化活动中心。' }
    ]
  },
  {
    id: 'samovar-tea-lounge',
    name: '萨莫瓦尔茶室',
    nameEn: 'Samovar Tea Lounge',
    continent: '北美洲',
    country: '美国',
    province: '加利福尼亚州',
    city: '旧金山',
    address: '菲尔莫尔街、海特区',
    established: '2002年',
    style: '现代东方风格茶室',
    specialty: '世界各地精品茶、茶调饮品、茶餐',
    highlight: '旧金山现代茶文化的代表，在全美拥有多家分店',
    imageIcon: '☕',
    color: '#FF5722',
    description: 'Samovar Tea Lounge（萨莫瓦尔茶室）是旧金山现代茶文化的代表，2002年由Jesse Jacobs创立。“Samovar”一词即俄语的茶炊，体现了其融合东西方茶文化的理念。萨莫瓦尔茶室不仅提供来自世界各地的精品茶，还创新了茶调饮品和茶餐，将传统茶文化与现代都市生活完美结合。',
    teas: ['sencha','matcha','darjeeling','earl-grey','jasmine-green','puer-sheng'],
    tags: ['旧金山','萨莫瓦尔','现代茶','茶调饮品','菲尔莫尔街','海特区'],
    chronology: [
      { period: '2000-2002年', title: '创立理念', content: '2000年代初，创始人Jesse Jacobs环游世界，体验了各国茶文化，萌生了将世界茶文化带到旧金山的想法。2002年，第一家Samovar Tea Lounge在菲尔莫尔街开业。' },
      { period: '2002-2010年', title: '旧金山扩张', content: '2002年至2010年，Samovar在旧金山连续开设了多家分店——海特区、索玛区、轮渡大厦等，成为旧金山最具影响力的茶馆品牌。' },
      { period: '2010-2020年', title: '全美扩张', content: '2010年代，Samovar开始向美国其他城市扩张，在洛杉矶、波特兰、西雅图等地开设分店，并推出了自有茶叶品牌。' },
      { period: '2020年至今', title: '数字化与全球化', content: '2020年以来，Samovar加大了线上业务投入，并开始向国际市场扩张，希望将现代茶文化理念传播到全世界。' }
    ]
  },
  {
    id: 'ching-ching-cha',
    name: '清清茶',
    nameEn: 'Ching Ching Cha',
    continent: '北美洲',
    country: '美国',
    province: '华盛顿特区',
    city: '华盛顿',
    address: '乔治城',
    established: '1998年',
    style: '中式传统茶馆',
    specialty: '中国六大茶类、传统中国茶点、茶道表演',
    highlight: '华盛顿特区最著名的中式茶馆，美国众议院和参议院议员常去的地方',
    imageIcon: '🀄',
    color: '#C0392B',
    description: 'Ching Ching Cha（清清茶）位于华盛顿特区乔治城，是美国首都最著名的中式茶馆。自1998年开业以来，清清茶以正宗的中国六大茶类、传统中国茶点和专业的茶道表演，成为华盛顿政界、商界和文化界人士常去的地方——甚至美国众议院和参议院议员也会在这里喝茶。',
    teas: ['biluochun','longjing','tieguanyin','dahongpao','qimen-hongcha','puer-sheng'],
    tags: ['华盛顿特区','乔治城','中式茶馆','中国茶','茶道表演','议员茶聚'],
    chronology: [
      { period: '1990年代初', title: '华盛顿的中国茶梦想', content: '1990年代初，来自中国的移民在华盛顿定居，发现这座国际大都市缺少一家专业的中式茶馆。1998年，Ching Ching Cha在乔治城开业——这是华盛顿第一家以专业中国茶文化为特色的茶馆。' },
      { period: '1998-2008年', title: '华府文化地标', content: '1998年至2008年，Ching Ching Cha迅速成为华盛顿文化生活的一部分——政治家在这里会谈，外交官在这里社交，学生在这里学习中国文化。' },
      { period: '2008-2020年', title: '奥巴马时代', content: '2008年奥巴马当选总统后，乔治城成为美国政治社交中心，Ching Ching Cha更是成为议员们常去的非正式会面场所。' },
      { period: '2020年至今', title: '后疫情时代', content: '2020年疫情期间，Ching Ching Cha通过线上销售茶叶和茶点维持经营，如今继续在乔治城传播中国茶文化。' }
    ]
  },
  {
    id: 'casa-de-cha-rainha',
    name: '女王茶馆',
    nameEn: 'Casa de Chá da Rainha',
    continent: '南美洲',
    country: '巴西',
    province: '圣保罗州',
    city: '圣保罗',
    address: '植物园内',
    established: '1950年代',
    style: '巴西现代主义风格茶室',
    specialty: '巴西本地茶、南美洲草本茶、咖啡',
    highlight: '圣保罗植物园内的地标茶室，现代主义建筑杰作',
    imageIcon: '🌿',
    color: '#1976D2',
    description: 'Casa de Chá da Rainha（女王茶馆）位于巴西圣保罗植物园内，是这座城市的地标性茶室。茶室建于1950年代，采用巴西现代主义建筑风格，玻璃幕墙面向植物园开放，阳光、植物与茶完美融合。这里供应巴西本地茶叶、南美洲草本茶和咖啡，是圣保罗人周末休闲的绝佳去处。',
    teas: ['brazil-tea','argentina-yerba-mate','south-africa-rooibos','chamomile'],
    tags: ['圣保罗','植物园','巴西','现代主义','南美洲茶','咖啡'],
    chronology: [
      { period: '1950年代', title: '植物园茶室建造', content: '1950年代，圣保罗植物园进行扩建，规划在园内建造一座茶室，为游客提供休憩场所。建筑采用当时流行的巴西现代主义风格，玻璃幕墙与自然环境完美融合。' },
      { period: '1950-1980年', title: '圣保罗地标', content: '1950年代至1980年代，女王茶馆成为圣保罗家庭周末郊游必去之地——逛植物园，然后在茶室喝茶，是圣保罗几代人的集体记忆。' },
      { period: '1980-2010年', title: '翻新与保护', content: '1980年代和2000年代，茶室进行了两次翻新，既保留了现代主义建筑的原貌，又升级了设施。这一时期，巴西本地茶叶种植也开始复兴，茶室菜单中增加了更多本地茶品。' },
      { period: '2010年至今', title: '当代茶旅', content: '2010年以来，女王茶馆成为圣保罗旅游打卡地，也是巴西茶文化复兴的重要场所之一。' }
    ]
  },
  {
    id: 'el-tezalte',
    name: '特萨尔特茶室',
    nameEn: 'El Tezalte',
    continent: '南美洲',
    country: '阿根廷',
    province: '布宜诺斯艾利斯',
    city: '布宜诺斯艾利斯',
    address: '圣特尔莫区',
    established: '1990年代',
    style: '南美马黛茶传统风格',
    specialty: '阿根廷马黛茶、南美草本茶、传统点心',
    highlight: '布宜诺斯艾利斯最著名的马黛茶主题茶馆，圣特尔莫区地标',
    imageIcon: '🥤',
    color: '#FFC107',
    description: 'El Tezalte（特萨尔特茶室）位于阿根廷布宜诺斯艾利斯的圣特尔莫区——这座城市最具波西米亚风情的街区。茶室以阿根廷传统马黛茶为主题，同时也供应南美其他国家的草本茶和传统点心。圣特尔莫区是布宜诺斯艾利斯的文化中心，这里周末有露天市集，游客如织，El Tezalte因此成为体验阿根廷马黛茶文化的绝佳地点。',
    teas: ['argentina-yerba-mate','brazil-tea','south-africa-rooibos','chamomile'],
    tags: ['布宜诺斯艾利斯','圣特尔莫','阿根廷','马黛茶','南美茶','市集'],
    chronology: [
      { period: '1990年代初', title: '圣特尔莫马黛茶馆', content: '1990年代初，圣特尔莫区开始复兴，成为布宜诺斯艾利斯的文化和旅游中心。在这一背景下，El Tezalte作为一家以马黛茶为主题的茶馆开业，希望向游客和本地人推广阿根廷传统茶文化。' },
      { period: '1990-2010年', title: '旅游地标', content: '1990年代至2010年代，随着圣特尔莫区周末露天市集越来越受欢迎，El Tezalte也成为游客体验马黛茶的首选地点——在这里可以品尝正宗的阿根廷马黛茶，还可以购买马黛茶茶具作为纪念品。' },
      { period: '2010年至今', title: '文化复兴', content: '2010年以来，阿根廷年轻一代对马黛茶文化重新产生兴趣，El Tezalte不仅是旅游打卡地，也成为本地年轻人聚会和社交的场所。' }
    ]
  },
  {
    id: 'casa-de-cha-curitiba',
    name: '库里蒂巴茶馆',
    nameEn: 'Casa de Chá',
    continent: '南美洲',
    country: '巴西',
    province: '巴拉那州',
    city: '库里蒂巴',
    address: '植物园温室旁',
    established: '1990年代',
    style: '现代温室风格茶室',
    specialty: '巴拉那本地茶、巴西茶、南美草本茶',
    highlight: '库里蒂巴植物园温室旁的标志性茶室，城市生态旅游的一部分',
    imageIcon: '🌿',
    color: '#4CAF50',
    description: 'Casa de Chá（库里蒂巴茶馆）位于巴西库里蒂巴植物园内，紧邻著名的玻璃温室——这座温室是库里蒂巴的城市地标，也是巴西最著名的现代主义建筑之一。茶馆采用与温室呼应的玻璃钢结构，面向植物园开放，在这里喝茶可以同时欣赏到温室和植物园的美景。',
    teas: ['brazil-tea','argentina-yerba-mate','south-africa-rooibos','chamomile'],
    tags: ['库里蒂巴','巴拉那','植物园','温室','巴西茶','生态旅游'],
    chronology: [
      { period: '1980-1990年', title: '植物园与温室', content: '1980年代，库里蒂巴作为巴西“生态城市”名片，建设了标志性的植物园和玻璃温室——这座温室模仿伦敦水晶宫，成为库里蒂巴最著名的地标。' },
      { period: '1990年代', title: '茶室建立', content: '1990年代，为了完善植物园的旅游设施，在温室旁建造了Casa de Chá茶室，采用与温室呼应的现代建筑风格，让游客在欣赏植物的同时可以品茶休憩。' },
      { period: '1990-2020年', title: '生态旅游地标', content: '1990年代至2020年代，随着库里蒂巴生态旅游越来越受欢迎，Casa de Chá也成为游客必去的打卡地，在这里不仅可以品茶，还可以了解巴西本地的茶文化。' },
      { period: '2020年至今', title: '可持续发展', content: '2020年以来，Casa de Chá致力于可持续发展，使用本地茶叶和可降解餐具，成为库里蒂巴生态城市理念的体现。' }
    ]
  }
];
